export enum QuickActionCode {
  PROPOSE_MEETING = 'PROPOSE_MEETING',
  SHARE_AVAILABILITY = 'SHARE_AVAILABILITY',
  CONFIRM_INTEREST_STILL_ACTIVE = 'CONFIRM_INTEREST_STILL_ACTIVE',
  MARK_ON_THE_WAY = 'MARK_ON_THE_WAY',
  REQUEST_CONTACT = 'REQUEST_CONTACT',
}
