export const PROFILE_LIMITS = {
  MAX_REACH_ZONES_PER_USER: 10,
  MAX_BIO_LENGTH: 280,
  MAX_FIRST_NAME_LENGTH: 80,
  MAX_LAST_NAME_LENGTH: 80,
  MAX_INSTAGRAM_HANDLE_LENGTH: 64,
  MAX_CITY_LENGTH: 120,
  MAX_ZONE_LENGTH: 120,
} as const;
