export const LISTING_LIMITS = {
  MIN_PHOTOS_TO_SUBMIT: 2,
  MAX_PHOTOS_PER_LISTING: 8,
  MAX_DESCRIPTION_LENGTH: 1000,
  MAX_TRADE_PREFERENCE_NOTES_LENGTH: 280,
  MAX_ACTIVE_LISTINGS_PER_USER: 100,
  MAX_PRICE_ARS: 999_999_999,
  MAX_CATEGORY_LENGTH: 80,
  MAX_SUBCATEGORY_LENGTH: 80,
  MAX_SIZE_LENGTH: 32,
  MAX_CONDITION_LENGTH: 32,
  MAX_BRAND_LENGTH: 120,
  MAX_COLOR_LENGTH: 80,
  MAX_MATERIAL_LENGTH: 120,
  MAX_CITY_LENGTH: 120,
  MAX_ZONE_LENGTH: 120,
  DEFAULT_LIST_LIMIT: 20,
  MAX_LIST_LIMIT: 50,
} as const;

export const FILE_LIMITS = {
  MAX_PHOTO_SIZE_BYTES: 8 * 1024 * 1024,
  MIN_PHOTO_WIDTH: 600,
  MIN_PHOTO_HEIGHT: 600,
  ALLOWED_IMAGE_MIME_TYPES: ['image/jpeg', 'image/png', 'image/webp'] as const,
} as const;
