export enum ListingState {
  DRAFT = 'DRAFT',
  IN_REVIEW = 'IN_REVIEW',
  OBSERVED = 'OBSERVED',
  PUBLISHED = 'PUBLISHED',
  PAUSED = 'PAUSED',
  RESERVED = 'RESERVED',
  CLOSED = 'CLOSED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
}
