export enum ModerationReasonCode {
  PHOTO_BLURRY = 'PHOTO_BLURRY',
  PHOTO_TOO_DARK = 'PHOTO_TOO_DARK',
  PHOTO_TOO_FEW = 'PHOTO_TOO_FEW',
  PHOTO_DUPLICATED = 'PHOTO_DUPLICATED',
  PHOTO_CONTENT_NOT_ALLOWED = 'PHOTO_CONTENT_NOT_ALLOWED',
  NOT_A_GARMENT = 'NOT_A_GARMENT',
  CATEGORY_MISMATCH = 'CATEGORY_MISMATCH',
  MISSING_REQUIRED_DATA = 'MISSING_REQUIRED_DATA',
  LOW_LISTING_QUALITY = 'LOW_LISTING_QUALITY',
}
