export enum NotificationType {
  PURCHASE_INTENT_RECEIVED = 'PURCHASE_INTENT_RECEIVED',
  TRADE_PROPOSAL_RECEIVED = 'TRADE_PROPOSAL_RECEIVED',
  INTERACTION_ACCEPTED = 'INTERACTION_ACCEPTED',
  INTERACTION_REJECTED = 'INTERACTION_REJECTED',
  NEW_CONVERSATION_MESSAGE = 'NEW_CONVERSATION_MESSAGE',
  LISTING_OBSERVED = 'LISTING_OBSERVED',
  LISTING_REJECTED = 'LISTING_REJECTED',
  RESERVATION_EXPIRING = 'RESERVATION_EXPIRING',
  RESERVATION_EXPIRED = 'RESERVATION_EXPIRED',
  MATCH_COMPLETED = 'MATCH_COMPLETED',
}
