export const INTERACTION_LIMITS = {
  MAX_ACTIVE_PURCHASE_INTENTS_PER_USER: 50,
  MAX_ACTIVE_TRADE_PROPOSALS_PER_USER: 50,
  MAX_PROPOSED_ITEMS_PER_TRADE_PROPOSAL: 5,
  MIN_PROPOSED_ITEMS_PER_TRADE_PROPOSAL: 1,
  MAX_SOURCE_LENGTH: 40,
} as const;
